FROM centos:8

RUN dnf -y install python3 \
  gcc \
  python3-devel

RUN pip3 install "virtualenv<20"

RUN mkdir /tmp/requirements/
ADD requirements.txt /tmp/requirements/

RUN virtualenv /venv
RUN /venv/bin/pip3 install -r /tmp/requirements/requirements.txt

COPY ./dist/towerdashboard-*.tar.gz /tmp/
RUN /venv/bin/pip3 install /tmp/towerdashboard-*.tar.gz

CMD ["bash"]
